var artworks = [
    {
      title: 'Analyse',
      serie: 'portrait',
      price: '€1000',
      matiere : 'Huile sur toile',
      format: "90x110",
      sold : '',
      description: 'Description de l\'œuvre...',
      imageUrl: 'img/Analyse.jpg',
    },
    {
        title: 'Dame Blanche',
        format : "150x80",
        serie: 'portrait_baroque',
        matiere : 'Huile sur toile',
        price: '€1000',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/Dameblanche.jpg',
    },
    {
        title: 'Interiorite',
        format: "150x80",
        serie: 'portrait',
        matiere : 'Huile sur toile',
        price: '€1000',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/Interiorite.jpg',
    },    
    {
        title: 'Julien et margueritte',
        serie: 'ravalet',
        matiere : 'Huile sur toile',
        format: "90x110",
        price: '€1000',
        sold : 'Vendu',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/JulienMargueritte.jfif',
    },
    {
        title: 'Maison du port',
        serie: 'paysage',
        matiere : 'Huile sur toile',
        format:"185x100",
        sold : '',
        price: '€1000',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/Maison-du-port.jpg',
    },
    {
        title: 'Memoire',
        serie: 'portrait',
        format: "90x110",
        matiere : 'Huile sur toile',
        price: '€1000',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/memoire.jpg',
        },
    {
        title: 'Vibration',
        serie: 'portrait',
        format: "90x110",
        matiere : 'Huile sur toile',
        price: '€1000',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/vibration.jpg',
    },
    {
        title: 'Roses noires',
        serie: 'portrait_baroque',
        format: "90x110",
        matiere : 'Huile sur toile',
        price: '€1000',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/roses_noires.jfif',
    },
    {
        title: 'Nocturne',
        serie: 'paysage',
        format: "90x110",
        matiere : 'Huile sur toile',
        price: '€1000',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/nocturne.jpg',
    },
    {
        title: 'Reine',
        serie: 'portrait_baroque',
        format: "90x110",
        matiere : 'Huile sur toile',
        price: '€1000',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/reine.jpg',
    },
    {
        title: 'Point de vue',
        serie: 'portrait',
        matiere : 'Huile sur toile',
        format: "90x110",
        price: '€1000',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/point-de-vue.jpg',
    },
    {
        title: 'Cap levi',
        serie: 'paysage',
        matiere : 'Acrylique sur toile',
        format: "50x70",
        price: '€700',
        sold : '',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/Cap-levi.jpg',
    },
    {

        title: 'Les amants',
        serie: 'paysage',
        matiere : 'Peinture / Acrylique / Pastel / Collages',
        format: "70x80",
        price: '€1800',
        sold : 'Vendu',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/les-amants.jfif',

    },
    {

        title: 'Femme et fleurs',
        serie: 'portrait_baroque',
        matiere : 'Acrylique sur toile',
        format: "70x60",
        price: '€1800',
        sold : 'Vendu',
        description: 'Description de l\'œuvre...',
        imageUrl: 'img/elle_fleur.jpg',

    }
  ];
  
  function openArtwork(artworkId) {
    window.location.href = 'artwork.html?id=' + encodeURIComponent(artworkId);
}
